#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
把「这个工坊物品到底依赖谁」在本机查清楚，并把可点击的依赖链接写进 workshop.txt。

为什么需要它
------------
游戏的 `workshop.txt` **只有 6 个合法键**（`version / id / title / description / tags / visibility`），
**没有任何声明依赖的键** —— 字节码 `SteamWorkshopItem.readWorkshopTxt()` 里就这 6 个字符串；
往里面写 `required=…` 会被静默丢掉（实测：description 字节数逐字节不变）。
而游戏对接 Steam 的 native 只有 `n_SetItemTitle/Description/Visibility/Tags/Content/Preview/SubmitItemUpdate`，
**没有设置依赖的接口** —— 所以 Steam 页面上的「必需物品（Required Items）」只能在网页/客户端手填，每个物品一次。

本工具做两件事：
  1. `--check`（默认）：把「物品 → 它 ship 的 mod → require/loadModAfter → 对应工坊 id」列成表，
     并给出**需要在网页上填的 id 清单**；
  2. `--write <物品目录名>…`：把一段**可点击的依赖小节**写进这些物品的 `workshop.txt`
     （游戏里 `description=` 支持多媒体行；Steam 网页会把 `[url]` 渲染成链接）。
     块内容用 `#` 注释做标记 —— `#` 开头的行被 readWorkshopTxt 整行跳过，所以标记不会进简介。

mod id → 工坊 id 的对照从**本机已订阅的工坊内容**反查（`workshop/content/108600/<id>/**/mod.info` 的 `id=`），
再叠加本仓库自己物品的 `workshop.txt` 的 `id=`。查不到的一律标 `unknown`，绝不猜。

用法：
    python3 workshop_requires.py                       # 全仓库只读报告
    python3 workshop_requires.py --item bin2_npc_extension
    python3 workshop_requires.py --write bin2_npc_extension bin2_ProjectALifeNPCs_extensions
    python3 workshop_requires.py --workshop-root "/path/to/108600"
"""

from __future__ import annotations

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_REPO = os.path.dirname(os.path.dirname(HERE))          # bin2_workshop_upload_fix/ -> 仓库根
DEFAULT_WORKSHOP = os.path.expanduser(
    "~/Library/Application Support/Steam/steamapps/workshop/content/108600")

FILE_URL = "https://steamcommunity.com/sharedfiles/filedetails/?id=%s"
BEGIN = "# >>> bin2:workshop-requires (generated by tools/workshop_requires.py; do not edit by hand) >>>"
END = "# <<< bin2:workshop-requires <<<"
# 一个物品的依赖多到这个数就不再自动生成链接（例如 bin2_b42 的 modpack，require 里有 200+ 个）
WRITE_LIMIT = 12

MOD_INFO_KEYS = ("id", "name", "require", "loadModAfter")


# ----------------------------------------------------------------- 解析 mod.info

def parse_mod_info(path):
    """读 mod.info 的字段；值与文件里一样保留大小写，只去掉首尾空白。"""
    fields = {}
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            for raw in handle:
                line = raw.strip()
                if not line or line.startswith("#") or line.startswith("//"):
                    continue
                match = re.match(r"^(\w+)\s*=\s*(.*)$", line)
                if not match:
                    continue
                key, value = match.group(1), match.group(2).strip()
                if key in MOD_INFO_KEYS and key not in fields:
                    fields[key] = value
    except OSError:
        return {}
    return fields


def parse_list(value):
    """`require=` / `loadModAfter=` 的值：逗号分隔，逐项剥掉可能存在的反斜杠前缀。"""
    out = []
    for item in (value or "").split(","):
        name = item.strip().lstrip("\\").strip()
        if name:
            out.append(name)
    return out


def find_mod_infos(root, max_depth=5):
    """在 root 下找所有 mod.info（mods/<Mod>/[<ver>/]mod.info 两种布局都覆盖）。"""
    found = []
    base_depth = root.rstrip(os.sep).count(os.sep)
    for dirpath, dirnames, filenames in os.walk(root):
        if dirpath.count(os.sep) - base_depth >= max_depth:
            dirnames[:] = []
            continue
        if "mod.info" in filenames:
            found.append(os.path.join(dirpath, "mod.info"))
    return sorted(found)


# ----------------------------------------------------------------- 索引

def index_installed(workshop_root):
    """已订阅的工坊内容：mod id -> (workshop id, name)。后者用于生成链接文字。"""
    index = {}
    if not os.path.isdir(workshop_root):
        return index
    for entry in sorted(os.listdir(workshop_root)):
        item_dir = os.path.join(workshop_root, entry)
        if not os.path.isdir(item_dir) or not entry.isdigit():
            continue
        for info in find_mod_infos(item_dir, max_depth=4):
            fields = parse_mod_info(info)
            mod_id = (fields.get("id") or "").lstrip("\\").strip()
            if mod_id and mod_id not in index:
                index[mod_id] = (entry, fields.get("name") or mod_id)
    return index


def read_workshop_txt(path):
    """读物品根 workshop.txt 的键值（只关心 id/title）。"""
    fields = {}
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            for raw in handle:
                line = raw.strip()
                if not line or line.startswith("#") or line.startswith("//"):
                    continue
                if "=" not in line:
                    continue
                key, value = line.split("=", 1)
                if key in ("id", "title") and key not in fields:
                    fields[key] = value.strip()
    except OSError:
        pass
    return fields


def collect_items(repo, workshop_root):
    """仓库里所有工坊物品：一个含 workshop.txt 的目录就是一个物品。"""
    items = []
    for entry in sorted(os.listdir(repo)):
        item_dir = os.path.join(repo, entry)
        wtxt = os.path.join(item_dir, "workshop.txt")
        if not os.path.isfile(wtxt):
            continue
        mods = []
        for info in find_mod_infos(item_dir, max_depth=5):
            fields = parse_mod_info(info)
            if not fields.get("id"):
                continue
            mods.append({
                "id": fields["id"].lstrip("\\").strip(),
                "name": fields.get("name") or "",
                "require": parse_list(fields.get("require")),
                "loadModAfter": parse_list(fields.get("loadModAfter")),
                "info": info,
            })
        items.append({"dir": item_dir, "name": entry, "workshop": read_workshop_txt(wtxt), "mods": mods})
    return items


def build_index(repo, items, workshop_root):
    """先收录本仓库自己的物品（它们的 id= 是权威的），再补已订阅的第三方。"""
    index = {}
    for item in items:
        wid = (item["workshop"].get("id") or "").strip()
        for mod in item["mods"]:
            if wid:
                index.setdefault(mod["id"], (wid, mod["name"] or mod["id"]))
    for mod_id, value in index_installed(workshop_root).items():
        index.setdefault(mod_id, value)
    return index


def dependencies_of(item):
    """把该物品所有 mod 的 require / loadModAfter 合并出来（require 优先）。"""
    required, optional = [], []
    for mod in item["mods"]:
        for mod_id in mod["require"]:
            if mod_id not in required:
                required.append(mod_id)
        for mod_id in mod["loadModAfter"]:
            if mod_id not in required and mod_id not in optional:
                optional.append(mod_id)
    return required, optional


# ----------------------------------------------------------------- 写入 workshop.txt

def render_block(required, optional, index):
    """生成依赖小节（每行一条 description=，# 行是给游戏忽略的标记）。"""
    lines = [BEGIN, "description=", "description=[h2]依赖（点开即订阅）[/h2]", "description=[list]"]
    for role, mod_ids in (("必需", required), ("可选 / 推荐", optional)):
        for mod_id in mod_ids:
            entry = index.get(mod_id)
            if entry is not None:
                wid, name = entry
                label = name if name and name != mod_id else mod_id
                lines.append(
                    "description=[*][%s] [url=%s]%s[/url]（mod id [b]%s[/b]）"
                    % (role, FILE_URL % wid, label, mod_id))
            else:
                lines.append("description=[*][%s] [b]%s[/b]（非工坊物品 / 未在本地找到）" % (role, mod_id))
    lines.append("description=[/list]")
    lines.append(END)
    return lines


def strip_block(lines):
    """去掉上一次生成的块（含前后的空行/padding，避免重复累积）。"""
    out, skipping = [], False
    for line in lines:
        stripped = line.strip()
        if stripped == BEGIN:
            skipping = True
            continue
        if stripped == END:
            skipping = False
            continue
        if not skipping:
            out.append(line)
    return out


def write_block(item, index, apply):
    """把块插到 `[ ALERT_CONFIG ]` 之前；没有那个块就追加到末尾。返回 (状态, 行数变化)。"""
    path = os.path.join(item["dir"], "workshop.txt")
    with open(path, "r", encoding="utf-8") as handle:
        original = handle.read().splitlines()

    required, optional = dependencies_of(item)
    if not required and not optional:
        return "skip: 无依赖", 0
    if len(required) + len(optional) > WRITE_LIMIT:
        return "skip: 依赖过多（%d 个，建议手写摘要）" % (len(required) + len(optional)), 0

    body = strip_block(original)
    block = render_block(required, optional, index)

    insert_at = None
    for i, line in enumerate(body):
        if line.strip().startswith("[ ALERT_CONFIG"):
            insert_at = i
            break
    if insert_at is None:
        for i, line in enumerate(body):
            if line.strip().startswith("tags="):
                insert_at = i
                break
    if insert_at is None:
        insert_at = len(body)
    elif insert_at > 0 and body[insert_at - 1].strip() != "":
        block = [""] + block

    updated = body[:insert_at] + block + [""] + body[insert_at:]
    if updated == original:
        return "ok: 已是最新", 0
    if apply:
        with open(path, "w", encoding="utf-8") as handle:
            handle.write("\n".join(updated).rstrip("\n") + "\n")
    return "ok: %s%d 行" % ("写入 " if apply else "将写入 ", len(updated) - len(original)), len(updated) - len(original)


# ----------------------------------------------------------------- 报告

def report(items, index, only=None):
    for item in items:
        if only and item["name"] not in only:
            continue
        required, optional = dependencies_of(item)
        print("=" * 96)
        wid = item["workshop"].get("id") or "(未发布)"
        print("%s\n  工坊 id      : %s\n  收录的 mod    : %s"
              % (item["name"], wid, ", ".join(m["id"] for m in item["mods"]) or "(无)"))
        for role, mod_ids in (("必需 (require=)", required), ("可选 (loadModAfter=)", optional)):
            if not mod_ids:
                continue
            print("  %s:" % role)
            for mod_id in mod_ids:
                entry = index.get(mod_id)
                if entry is None:
                    print("    - %-32s -> 未知（不在本机工坊内容里；若是 GitHub/自制模组请手填）" % mod_id)
                else:
                    print("    - %-32s -> %s  %s" % (mod_id, entry[0], FILE_URL % entry[0]))
        if not required and not optional:
            print("  依赖          : 无")


def main():
    parser = argparse.ArgumentParser(description="查清工坊物品的依赖并生成可点击链接")
    parser.add_argument("--repo", default=DEFAULT_REPO, help="仓库根（默认按脚本位置推断）")
    parser.add_argument("--workshop-root", default=DEFAULT_WORKSHOP, help="Steam 工坊内容目录 108600")
    parser.add_argument("--item", action="append", default=[], help="只看某个物品目录名（可重复）")
    parser.add_argument("--write", nargs="+", default=[], help="把依赖小节写进这些物品的 workshop.txt")
    args = parser.parse_args()

    items = collect_items(args.repo, args.workshop_root)
    if not items:
        print("没有找到任何含 workshop.txt 的物品目录：%s" % args.repo, file=sys.stderr)
        return 2
    index = build_index(args.repo, items, args.workshop_root)
    print("索引：%d 个 mod id（来自本仓库物品 + %s）\n" % (len(index), args.workshop_root))

    only = set(args.item) if args.item else None
    if args.write:
        only = set(args.write)
    report(items, index, only)

    if args.write:
        print("\n" + "=" * 96)
        print("写入 workshop.txt（块用 # 行标记，游戏解析时整行跳过）：")
        for item in items:
            if item["name"] in args.write:
                status, _ = write_block(item, index, apply=True)
                print("  %-34s %s" % (item["name"], status))
        print("\n下一步：用游戏自己的解析器复核 →")
        print("  bash %s/run.sh \"\" ~/Zomboid/Workshop/<物品>" % os.path.dirname(HERE) + "/pz_workshop_probe")
        print("  # 或者一次过： bin2_workshop_upload_fix/tools/pz_workshop_probe/check_all.sh")
    return 0


if __name__ == "__main__":
    sys.exit(main())
